### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by FelixWeichselgartner** [devmarcstorm/python-network-scanner#2]
Hi,

how can this have MIT-License, when python-nmap has GPLv3-License?

Greetings

**Comment by FelixWeichselgartner** [comment]
Maybe this applies: https://www.gnu.org/licenses/gpl-faq.html#WhatIfWorkIsShort ?
Or see: bwaldvogel/neighbourhood#3

**Comment by devmarcstorm** [comment]
Hello, thank you for bringing this to my attention.

Since I don't redistribute python-nmap, I assumed that the situation allows MIT licenses. Of course, I don't want to violate python-nmap's license. 

I'm doing some research (I'm not a lawyer, so I don't have much legal expertise). As soon as I have an answer, I will act accordingly and comment on the decision in this issue.

Best regards and thanks again

**Comment by devmarcstorm** [comment]
Ok, so as far as I understand it now, network.py must be licensed under the GPL license since it requires python-nmap. This also applies to my main.py since it uses network.py.

I think multi-licensing would be too confusing. To be safe, I will change the license of the entire project to GPLv3 to avoid violating python-nmap's GPL license.

> Some sources on this subject (mostly discussions):
> https://www.gnu.org/licenses/gpl-3.0.en.html
> https://opensource.stackexchange.com/questions/6224/using-oss-of-different-licenses-in-mit-licensed-software
> https://en.wikipedia.org/wiki/License_compatibility
> https://opensource.stackexchange.com/questions/1640/if-im-using-a-gpl-3-library-in-my-project-can-i-license-my-project-under-mit-l
> https://gist.github.com/kn9ts/cbe95340d29fc1aaeaa5dd5c059d2e60


Best regards

**Comment by devmarcstorm** [comment]
Perhaps this could also fall under the linking exception. `¯\_(°_°)_/¯`
https://en.m.wikipedia.org/wiki/GPL_linking_exception

However... https://en.wikipedia.org/wiki/GNU_General_Public_License#Linking_and_derived_works

**Comment by FelixWeichselgartner** [comment]
@devmarcstorm I had a similar case at work where I wanted to use a python library that is LGPL3 licensed in a commercial product. I also did some research (I'm no lawyer either) and as it seems GLP3 is "written" for C++ code. A python import is not considered dynamically linked and as far as I know there is not possibility to dynamically link in python. (That was the post i read: https://stackoverflow.com/questions/40492518/is-an-import-in-python-considered-to-be-dynamic-linking)
Therefore, the company I work for has the rule: no GPL licensed work (not even LGPL).

**Comment by devmarcstorm** [comment]
That's interesting @FelixWeichselgartner. Someone I just talked to told me about a similar arrangement at his former company.
